#############################################################################
# Makefile for building: MyselfWord
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  MyselfWord.pro
# Template: app
# Command: /usr/lib/alpha-linux-gnu/qt5/bin/qmake -o Makefile MyselfWord.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++ -I. -isystem /usr/include/alpha-linux-gnu/qt5 -isystem /usr/include/alpha-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/alpha-linux-gnu/qt5/QtWidgets -isystem /usr/include/alpha-linux-gnu/qt5/QtGui -isystem /usr/include/alpha-linux-gnu/qt5/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/lib/alpha-linux-gnu -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/alpha-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ubuilder.cpp \
		uchild.cpp \
		uprojectwizard.cpp \
		uprojectnavbar.cpp \
		unavigation.cpp \
		ueditwindow.cpp \
		uoutputwindow.cpp \
		uhighlighter.cpp qrc_resources.cpp \
		moc_ubuilder.cpp \
		moc_uchild.cpp \
		moc_uprojectwizard.cpp \
		moc_uprojectnavbar.cpp \
		moc_unavigation.cpp \
		moc_ueditwindow.cpp \
		moc_uoutputwindow.cpp
OBJECTS       = main.o \
		ubuilder.o \
		uchild.o \
		uprojectwizard.o \
		uprojectnavbar.o \
		unavigation.o \
		ueditwindow.o \
		uoutputwindow.o \
		uhighlighter.o \
		qrc_resources.o \
		moc_ubuilder.o \
		moc_uchild.o \
		moc_uprojectwizard.o \
		moc_uprojectnavbar.o \
		moc_unavigation.o \
		moc_ueditwindow.o \
		moc_uoutputwindow.o
DIST          = /usr/lib/alpha-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/lex.prf \
		MyselfWord.pro main.cpp \
		ubuilder.cpp \
		uchild.cpp \
		uprojectwizard.cpp \
		uprojectnavbar.cpp \
		unavigation.cpp \
		ueditwindow.cpp \
		uoutputwindow.cpp \
		uhighlighter.cpp
QMAKE_TARGET  = MyselfWord
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = MyselfWord


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MyselfWord.pro /usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/alpha-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/lex.prf \
		MyselfWord.pro \
		resources.qrc \
		/usr/lib/alpha-linux-gnu/libQt5PrintSupport.prl \
		/usr/lib/alpha-linux-gnu/libQt5Widgets.prl \
		/usr/lib/alpha-linux-gnu/libQt5Gui.prl \
		/usr/lib/alpha-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile MyselfWord.pro
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/alpha-linux-gnu/qt5/mkspecs/features/lex.prf:
MyselfWord.pro:
resources.qrc:
/usr/lib/alpha-linux-gnu/libQt5PrintSupport.prl:
/usr/lib/alpha-linux-gnu/libQt5Widgets.prl:
/usr/lib/alpha-linux-gnu/libQt5Gui.prl:
/usr/lib/alpha-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MyselfWord.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/MyselfWord1.0.0 || mkdir -p .tmp/MyselfWord1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/MyselfWord1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/MyselfWord1.0.0/ && $(COPY_FILE) --parents ubuilder.h uchild.h uprojectwizard.h uprojectnavbar.h unavigation.h ueditwindow.h uoutputwindow.h uhighlighter.h .tmp/MyselfWord1.0.0/ && $(COPY_FILE) --parents main.cpp ubuilder.cpp uchild.cpp uprojectwizard.cpp uprojectnavbar.cpp unavigation.cpp ueditwindow.cpp uoutputwindow.cpp uhighlighter.cpp .tmp/MyselfWord1.0.0/ && (cd `dirname .tmp/MyselfWord1.0.0` && $(TAR) MyselfWord1.0.0.tar MyselfWord1.0.0 && $(COMPRESS) MyselfWord1.0.0.tar) && $(MOVE) `dirname .tmp/MyselfWord1.0.0`/MyselfWord1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MyselfWord1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		images/filesave.png \
		images/fileopen.png \
		images/editundo.png \
		images/editredo.png \
		images/filenew.png \
		images/editcut.png \
		images/editpaste.png \
		images/build.png \
		images/editcopy.png \
		images/fileprint.png \
		images/settings.png
	/usr/lib/alpha-linux-gnu/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_ubuilder.cpp moc_uchild.cpp moc_uprojectwizard.cpp moc_uprojectnavbar.cpp moc_unavigation.cpp moc_ueditwindow.cpp moc_uoutputwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ubuilder.cpp moc_uchild.cpp moc_uprojectwizard.cpp moc_uprojectnavbar.cpp moc_unavigation.cpp moc_ueditwindow.cpp moc_uoutputwindow.cpp
moc_ubuilder.cpp: unavigation.h \
		uoutputwindow.h \
		ueditwindow.h \
		ubuilder.h
	/usr/lib/alpha-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++ -I/root/uoldev/MyselfWord -I/usr/include/alpha-linux-gnu/qt5 -I/usr/include/alpha-linux-gnu/qt5/QtPrintSupport -I/usr/include/alpha-linux-gnu/qt5/QtWidgets -I/usr/include/alpha-linux-gnu/qt5/QtGui -I/usr/include/alpha-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9.1 -I/usr/include/c++/4.9.1/alphaev6-unknown-linux-gnu -I/usr/include/c++/4.9.1/backward -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include-fixed -I/usr/local/include -I/usr/include ubuilder.h -o moc_ubuilder.cpp

moc_uchild.cpp: uhighlighter.h \
		uchild.h
	/usr/lib/alpha-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++ -I/root/uoldev/MyselfWord -I/usr/include/alpha-linux-gnu/qt5 -I/usr/include/alpha-linux-gnu/qt5/QtPrintSupport -I/usr/include/alpha-linux-gnu/qt5/QtWidgets -I/usr/include/alpha-linux-gnu/qt5/QtGui -I/usr/include/alpha-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9.1 -I/usr/include/c++/4.9.1/alphaev6-unknown-linux-gnu -I/usr/include/c++/4.9.1/backward -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include-fixed -I/usr/local/include -I/usr/include uchild.h -o moc_uchild.cpp

moc_uprojectwizard.cpp: uprojectwizard.h
	/usr/lib/alpha-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++ -I/root/uoldev/MyselfWord -I/usr/include/alpha-linux-gnu/qt5 -I/usr/include/alpha-linux-gnu/qt5/QtPrintSupport -I/usr/include/alpha-linux-gnu/qt5/QtWidgets -I/usr/include/alpha-linux-gnu/qt5/QtGui -I/usr/include/alpha-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9.1 -I/usr/include/c++/4.9.1/alphaev6-unknown-linux-gnu -I/usr/include/c++/4.9.1/backward -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include-fixed -I/usr/local/include -I/usr/include uprojectwizard.h -o moc_uprojectwizard.cpp

moc_uprojectnavbar.cpp: uprojectnavbar.h
	/usr/lib/alpha-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++ -I/root/uoldev/MyselfWord -I/usr/include/alpha-linux-gnu/qt5 -I/usr/include/alpha-linux-gnu/qt5/QtPrintSupport -I/usr/include/alpha-linux-gnu/qt5/QtWidgets -I/usr/include/alpha-linux-gnu/qt5/QtGui -I/usr/include/alpha-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9.1 -I/usr/include/c++/4.9.1/alphaev6-unknown-linux-gnu -I/usr/include/c++/4.9.1/backward -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include-fixed -I/usr/local/include -I/usr/include uprojectnavbar.h -o moc_uprojectnavbar.cpp

moc_unavigation.cpp: unavigation.h
	/usr/lib/alpha-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++ -I/root/uoldev/MyselfWord -I/usr/include/alpha-linux-gnu/qt5 -I/usr/include/alpha-linux-gnu/qt5/QtPrintSupport -I/usr/include/alpha-linux-gnu/qt5/QtWidgets -I/usr/include/alpha-linux-gnu/qt5/QtGui -I/usr/include/alpha-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9.1 -I/usr/include/c++/4.9.1/alphaev6-unknown-linux-gnu -I/usr/include/c++/4.9.1/backward -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include-fixed -I/usr/local/include -I/usr/include unavigation.h -o moc_unavigation.cpp

moc_ueditwindow.cpp: ueditwindow.h
	/usr/lib/alpha-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++ -I/root/uoldev/MyselfWord -I/usr/include/alpha-linux-gnu/qt5 -I/usr/include/alpha-linux-gnu/qt5/QtPrintSupport -I/usr/include/alpha-linux-gnu/qt5/QtWidgets -I/usr/include/alpha-linux-gnu/qt5/QtGui -I/usr/include/alpha-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9.1 -I/usr/include/c++/4.9.1/alphaev6-unknown-linux-gnu -I/usr/include/c++/4.9.1/backward -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include-fixed -I/usr/local/include -I/usr/include ueditwindow.h -o moc_ueditwindow.cpp

moc_uoutputwindow.cpp: uoutputwindow.h
	/usr/lib/alpha-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/alpha-linux-gnu/qt5/mkspecs/linux-g++ -I/root/uoldev/MyselfWord -I/usr/include/alpha-linux-gnu/qt5 -I/usr/include/alpha-linux-gnu/qt5/QtPrintSupport -I/usr/include/alpha-linux-gnu/qt5/QtWidgets -I/usr/include/alpha-linux-gnu/qt5/QtGui -I/usr/include/alpha-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9.1 -I/usr/include/c++/4.9.1/alphaev6-unknown-linux-gnu -I/usr/include/c++/4.9.1/backward -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include -I/usr/lib/gcc/alphaev6-unknown-linux-gnu/4.9.1/include-fixed -I/usr/local/include -I/usr/include uoutputwindow.h -o moc_uoutputwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ubuilder.h \
		unavigation.h \
		uoutputwindow.h \
		ueditwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ubuilder.o: ubuilder.cpp ubuilder.h \
		unavigation.h \
		uoutputwindow.h \
		ueditwindow.h \
		uchild.h \
		uhighlighter.h \
		uprojectwizard.h \
		uprojectnavbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ubuilder.o ubuilder.cpp

uchild.o: uchild.cpp uchild.h \
		uhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uchild.o uchild.cpp

uprojectwizard.o: uprojectwizard.cpp uprojectwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uprojectwizard.o uprojectwizard.cpp

uprojectnavbar.o: uprojectnavbar.cpp uprojectnavbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uprojectnavbar.o uprojectnavbar.cpp

unavigation.o: unavigation.cpp unavigation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unavigation.o unavigation.cpp

ueditwindow.o: ueditwindow.cpp ueditwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ueditwindow.o ueditwindow.cpp

uoutputwindow.o: uoutputwindow.cpp uoutputwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uoutputwindow.o uoutputwindow.cpp

uhighlighter.o: uhighlighter.cpp uhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uhighlighter.o uhighlighter.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_ubuilder.o: moc_ubuilder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ubuilder.o moc_ubuilder.cpp

moc_uchild.o: moc_uchild.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uchild.o moc_uchild.cpp

moc_uprojectwizard.o: moc_uprojectwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uprojectwizard.o moc_uprojectwizard.cpp

moc_uprojectnavbar.o: moc_uprojectnavbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uprojectnavbar.o moc_uprojectnavbar.cpp

moc_unavigation.o: moc_unavigation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_unavigation.o moc_unavigation.cpp

moc_ueditwindow.o: moc_ueditwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ueditwindow.o moc_ueditwindow.cpp

moc_uoutputwindow.o: moc_uoutputwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uoutputwindow.o moc_uoutputwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

